### ISSUE TITLE
Growing degree days calculation method citation

### ISSUE THREAD

**Issue by mimas8000** [Nowosad/pollen#10]
I'm trying to understand how the growing degree day function `gdd(tmax, tmin, tbase, tbase_max)` works. Can you add a citation that details the calculation method to your documentation? The pollen gdd function gives me a little different result than some other methods e.g. "single triangle method" as described in the following citation. 
- _Zalom, F.G., Goodell, P.B., Wilson, L.T., Barnett, W.W. and Bentley, W.J., 1983. Degree-Days, the Calculation and Use of Heat Units in Pest Management: University of California Division of Agriculture and Natural Resources Leaflet 21373. University of California, Berkeley, CA._

**Comment by Nowosad** [comment]
Hi, @mimas8000 - thanks for opening this issue. You are the second person asking me this question this week.

The only GDD method available in the released version of **pollen** is presented as case C below (from Baskerville, G., & Emin, P. (1969). Rapid Estimation of Heat Accumulation from Maximum and Minimum Temperatures. Ecology, 50(3), 514-517. doi:10.2307/1933912): 

![Screenshot from 2020-02-12 09-42-31](https://user-images.githubusercontent.com/3457131/74317623-0e55aa00-4d7c-11ea-9121-68da485a9878.png)

However, I added a new option in the development version - `case`. It adds case B and D from the above-mentioned paper. You can install the development version from GitHub:

```R
remotes::install_github("nowosad/pollen")
```

I also created a new package vignette - https://nowosad.github.io/pollen/articles/gdd.html. 

Please take a look at the vignette and try the code by yourself. It still could have bugs, so I will be grateful for your feedback. Also, feel free to suggest any changes or improvements.

**Comment by mimas8000** [comment]
Thank you Jakub, this is immensely helpful! BTW I happen to be working with the other person who contacted you and I'll share this with them. I'll give the updated function a try:
 `gdd(tmax, tmin, tbase, tbase_max, case = "C")` 
Thanks also for developing this package. It's very useful.

**Comment by Nowosad** [comment]
@mimas8000 The updated version is on CRAN now.
